version: '2'
networks:
   cookbook:
     external: true
services:
  # django ---------------------------------------------------------------------
  django:
    image: cookbook/dn-django-development
    container_name: cookbook-dn-django-development
    command: /bin/sh -c "cd /opt/app; python3 manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    volumes:
      - ../../app/django/:/opt/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - SOCKETIO_SERVER_NAME=${SOCKETIO_SERVER_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - nodejs
      - postgres
      - redis
    networks:
      - cookbook

  # nodejs ---------------------------------------------------------------------
  nodejs:
    image: cookbook/dn-nodejs-development
    container_name: cookbook-dn-nodejs-development
    command: /bin/sh -c "forever start /usr/local/bin/node-inspector --web-port=${NODEJS_DEBUGGER_PORT}; cd /opt/app/ && supervisor --debug server.js"
    volumes:
      - ../../app/nodejs:/opt/app
    ports:
      - "${SOCKETIO_PORT}:${SOCKETIO_PORT}"
      - "${NODEJS_DEBUGGER_PORT}:${NODEJS_DEBUGGER_PORT}"
    environment:
      - NODE_PATH=/opt/node_modules/
      - SOCKETIO_PORT=${SOCKETIO_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - cookbook

  # postgres -------------------------------------------------------------------
  postgres:
    image: postgres
    container_name: cookbook-dn-postgresql-development
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "/var/lib/postgresql-cookbook:/var/lib/postgresql-cookbook"
    networks:
      cookbook:
        aliases:
          - ${POSTGRES_HOST}

  # redis ----------------------------------------------------------------------
  redis:
    image: redis
    container_name: cookbook-dn-redis-development
    networks:
      cookbook:
        aliases:
          - ${REDIS_HOST}
